apiVersion: v1
kind: Service
metadata:
  name: neotech-service
  namespace : neotech
spec:
  type: NodePort  # Expose l’application sur un port du nœud
  selector:
    app: neotech-app
  ports:
    - protocol: TCP
      port: 80        # Port du service interne
      targetPort: 3000  # Port du container
      nodePort: 30008  # Port exposé sur le nœud (doit être entre 30000-32767)
